django_forum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
#    url(r'^foundation/', include('foundation.urls')),
    url(r'^forum/', include('forumapp.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='welcome')
]

forumapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'forumapp'
urlpatterns = [
    url(r'^settings/$', views.UserSettingsView.as_view(), name='settings'),
    url(r'^settings/(?P<channel>[-\w]+)/$', views.ChannelSettingsView.as_view(), name='channel_settings'),
    url(r'^favorites/$', views.FavoritesView.as_view(), name='favorites'),
    url(r'^user/(?P<username>[-\w]+)/$', views.UserView.as_view(), name='user'),
    url(r'^(?P<channel>[-\w]+)/(?P<thread>[0-9]+)/$', views.CommentView.as_view(), name='comment'),
    url(r'^(?P<channel>[-\w]+)/$', views.ThreadView.as_view(), name='thread'),
    url(r'^$', views.ChannelView.as_view(), name='channel'),
]

registration/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import SignUpView, LogInView, PasswordResetView, PasswordResetSuccessView

app_name = 'registration'
urlpatterns = [
    url(r'login/', LogInView, name='login'),
    url(r'logout/', auth_views.logout, {'template_name': 'registration/logout.html'}, name='logout'),
    url(r'signup/', SignUpView, name='signup'),
    url(r'password_reset/', PasswordResetView, name='password_reset'),
    url(r'password_reset_success/', PasswordResetSuccessView, name='password_reset_success'),
]

forumapp/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# manager that uses queryset with nulls last
class NullsLastManager(models.Manager):

    def get_queryset(self):
        return models.QuerySet(self.model, using=self._db).order_by(models.F('pin_date').asc(nulls_last=True), models.F('recent_date').desc())

# One-to-one with User
class UserSettings(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    favorites = models.TextField(default='[]')
    bio = models.TextField(max_length=250, default='Hello world')

    class Meta:
        pass

    def __str__(self):
        return self.user.get_username()

# Store channel_name as primary_key
class Channel(models.Model):
    objects = NullsLastManager()

    channel_name = models.SlugField(max_length=30, primary_key=True)
    description = models.CharField(max_length=250, default='')

    banned_users = models.TextField(default='[]')
    moderators = models.TextField(default='[]')
    pin_date = models.DateTimeField('date pinned', null=True)
    
    owner = models.ForeignKey(User, to_field="username", null=True, on_delete=models.SET_NULL)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    recent_date = models.DateTimeField('date used', default=timezone.now)

    class Meta:
        ordering = ['-recent_date']

    def __str__(self):
        return self.channel_name.replace('-', ' ')

    def is_recent(self):
        now = timezone.now()
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= now

    is_recent.admin_order_field = 'pub_date'
    is_recent.boolean = True
    is_recent.short_description = 'Published recently?'

# Store channel and thread_id as primary keys
class Thread(models.Model):
    objects = NullsLastManager()
    
    thread_id = models.IntegerField(default=0)
    channel = models.ForeignKey(Channel)
    
    thread_name = models.CharField(max_length=90)
    description = models.CharField(max_length=150)
    pin_date = models.DateTimeField('date pinned', null=True)
    
    owner = models.ForeignKey(User, to_field="username", null=True, on_delete=models.SET_NULL)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    recent_date = models.DateTimeField('date used', default=timezone.now)

    class Meta:
        unique_together = (('channel', 'thread_id'))
        ordering = ['pin_date', '-recent_date']

    def __str__(self):
        return self.thread_name

    # validate uniqueness on channel and thread_id
    def validate_unique(self, exclude=None):
        threads = Thread.objects.filter(channel=self.channel)
        if self._state.adding and threads.filter(thread_id=self.thread_id).exists():
            raise ValidationError({field:'' for field in self._meta.unique_together[0]})

    # override to auto set thread_id
    def save(self, *args, **kwargs):

        if self._state.adding:
            threads = Thread.objects.filter(channel=self.channel)

            last_id = threads.aggregate(largest=models.Max('thread_id'))['largest']

            if last_id is not None:
                self.thread_id = last_id + 1

        super(Thread, self).save(*args, **kwargs)

    def is_recent(self):
        now = timezone.now()
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= now

    is_recent.admin_order_field = 'pub_date'
    is_recent.boolean = True
    is_recent.short_description = 'Published recently?'

# Primary keys are thread and comment_id
class Comment(models.Model):
    comment_id = models.IntegerField(default=0)
    thread = models.ForeignKey(Thread)

    text = models.CharField(max_length=250)

    pub_date = models.DateTimeField('date published', default=timezone.now)
    owner = models.ForeignKey(User, to_field="username", null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = (('thread', 'comment_id'))
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

    # validate uniqueness on thread and comment_id
    def validate_unique(self, exclude=None):
        not_unique = Comment.objects.filter(thread=self.thread, comment_id=self.comment_id).exists()
        if self._state.adding and not_unique:
            raise ValidationError({field:'' for field in self._meta.unique_together[0]})

    # override to auto set comment_id
    def save(self, *args, **kwargs):

        if self._state.adding:
            comments = Comment.objects.filter(thread=self.thread)

            last_id = comments.aggregate(largest=models.Max('comment_id'))['largest']
            
            if last_id is not None:
                self.comment_id = last_id + 1

        #self.validate_unique()

        super(Comment, self).save(*args, **kwargs)

    # see if a comment was posted in the last day
    def is_recent(self):
        now = timezone.now()
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= now

    is_recent.admin_order_field = 'pub_date'
    is_recent.boolean = True
    is_recent.short_description = 'Published recently?'

forumapp/forms.py
from django.forms import ModelForm
from .models import UserSettings, Channel, Thread, Comment

class ChannelForm(ModelForm):
    class Meta:
        model = Channel
        fields = ['channel_name', 'description']

class ThreadForm(ModelForm):
    class Meta:
        model = Thread
        fields = ['thread_name', 'description']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class UserSettingsForm(ModelForm):
    class Meta:
        model = UserSettings
        fields = ['bio',]

forumapp/views.py
import json
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from django.urls import reverse
from django.forms.models import model_to_dict
from .models import UserSettings, Channel, Thread, Comment
from .forms import UserSettingsForm, ChannelForm, ThreadForm, CommentForm

## Get or create the user's settings (because get_or_create returns an annoying tuple)
def get_or_create_settings(user):
    us = UserSettings.objects.filter(user=user)
    if us.exists():
        return us.get()
    else:
        return UserSettings.objects.create(user=user)

## Return whether a user is an owner or moderator of the channel
def is_mod(obj, user):
    # retrieve channel regardless of if we have a channel, thread, or comment
    channel = isinstance(obj, Comment) and obj.thread.channel \
            or (isinstance(obj, Thread) and obj.channel or obj)

    # check if user is owner or moderator
    return user == channel.owner \
            or user.get_username() in json.loads(channel.moderators)

## Return whether a user is an owner of the channel
def is_owner(obj, user):
    # retrieve channel regardless of if we have a channel, thread, or comment
    channel = isinstance(obj, Comment) and obj.thread.channel \
            or (isinstance(obj, Thread) and obj.channel or obj)

    # check if user is owner
    return user == channel.owner

## Automatically lets views attach form and context_objects to the context if defined
class ViewMixin(generic.base.ContextMixin):
    initial = {'key': 'value'}

    def get_context_data(self, **kwargs):
        context = super(ViewMixin, self).get_context_data(**kwargs)

        if hasattr(self, 'form_class'):
            if hasattr(self, 'form_object'):

                #convert object to iterable for form constructor
                context['form'] = self.form_class(initial=model_to_dict(self.object))

            else:
                context['form'] = self.form_class(initial=self.initial)

        if hasattr(self, 'context_object_name'):
            context[self.context_object_name] = self.get_object()

        return context

# Show the settings menu
class UserSettingsView(ViewMixin, generic.DetailView):
    model = UserSettings
    template_name = 'forumapp/user_settings.html'

    form_class = UserSettingsForm

    queryset = UserSettings.objects

    def get_object(self):
        if self.request.user.is_authenticated:
            return get_or_create_settings(self.request.user)

        return self.queryset.none()

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.form_object = True

        if not hasattr(self, 'object'):
            raise Http404("User does not exist. Are you logged in?")

        return super(UserSettingsView, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if 'save' in request.POST:
            form = self.form_class(request.POST, instance=self.object)

            if form.is_valid():
                form.save()

            else:
                messages.error(request, "Invalid input")

        return HttpResponseRedirect(self.request.path_info)

# Show the channel settings menu
class ChannelSettingsView(ViewMixin, generic.DetailView):
    model = Channel
    template_name = 'forumapp/channel_settings.html'

    form_class = ChannelForm

    queryset = Channel.objects

    def get_object(self):
        if self.request.user.is_authenticated:
            channel_name = self.kwargs.get('channel')
            channel = self.queryset.filter(channel_name=channel_name)

            if channel.exists():
                return channel.get()

        return self.queryset.none()

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.form_object = True

        if not hasattr(self, 'object'):
            raise Http404("User does not exist. Are you logged in?")

        # make sure user is owner/mod/admin
        if not (request.user.is_staff or is_mod(self.object, request.user)):
            raise Http404("Insufficient permissions")

        return super(ChannelSettingsView, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        # make sure user is owner/mod/admin
        if not (request.user.is_staff or is_mod(self.object, request.user)):
            raise Http404("Insufficient permissions")

        if 'save' in request.POST:
            form = self.form_class(request.POST, instance=self.object)

            if form.is_valid():
                form.save()

            else:
                messages.error(request, "Invalid input")

        return HttpResponseRedirect(self.request.path_info)

# Create your views here.
class ChannelView(ViewMixin, generic.ListView):
    model = Channel
    template_name = 'forumapp/channel.html'

    form_class = ChannelForm

    queryset = Channel.objects
    context_object_name = 'channel_list'

    def get_object(self, exclude=None):
        return self.queryset.all()


    def post(self, request, *args, **kwargs):

        if 'add_favorite' in request.POST:
            settings = get_or_create_settings(self.request.user)
            favs = json.loads(settings.favorites)
            channel_name = request.POST['channel_name']

            favs.append(channel_name)
            settings.favorites = json.dumps(favs)
            settings.save()

        elif 'remove_favorite' in request.POST:
            settings = get_or_create_settings(self.request.user)
            favs = json.loads(settings.favorites)
            channel_name = request.POST['channel_name']

            favs = [c for c in favs if not c == channel_name]
            settings.favorites = json.dumps(favs)
            settings.save()

        elif 'pin' in request.POST:
            channel_name = request.POST['channel_name']
            channel = self.queryset.filter(channel_name=channel_name)

            if channel.exists():
                channel = channel.get()

                # Require staff status to pin channels
                if request.user.is_staff:
                    channel.pin_date = timezone.now()
                    channel.save()

        elif 'unpin' in request.POST:
            channel_name = request.POST['channel_name']
            channel = self.queryset.filter(channel_name=channel_name)

            if channel.exists():
                channel = channel.get()

                # Require staff status to unpin channels
                if request.user.is_staff:
                    channel.pin_date = None
                    channel.save()

        elif 'create' in request.POST:
            if not request.user.is_authenticated:
                messages.error(request, "Please log in to create channels.")
                
                return HttpResponseRedirect(self.request.path_info)

            owner = request.user
            channel = Channel(owner=owner)
            form = self.form_class(request.POST, instance=channel)

            if form.is_valid():
                channel_name = form.cleaned_data.get('channel_name')
                description = form.cleaned_data.get('description')

                if len(channel_name) > 3:
                    if len(description) > 5:

                        channel.save()
                        return HttpResponseRedirect(reverse('forumapp:thread', \
                                kwargs={'channel': channel_name}))

                    else:
                        channel.delete()
                        messages.error(request, "Channel description must be at least 6 characters.")

                else:
                    channel.delete()
                    messages.error(request, "Channel name must be at least 4 characters.")

            elif Channel.objects.filter(channel_name=form. data.get('channel_name')).exists():
                messages.error(request, "Channel already exists with that name.")

            else:
                channel.delete()
                messages.error(request, " Channel name must contain hyphens \
                        in place of whitespace and cannot contain symbols.")

        return HttpResponseRedirect(self.request.path_info)

class ThreadView(ViewMixin, generic.DetailView):
    model = Thread
    template_name = 'forumapp/thread.html'

    form_class = ThreadForm

    queryset = Thread.objects
    context_object_name = 'thread_list'

    # Return querylist of threads in the given channel
    def get_object(self):
        c_name = self.kwargs.get('channel')

        return self.queryset.filter(channel__channel_name=c_name)

    def post(self, request, *args, **kwargs):

        channel = Channel.objects.filter(channel_name=self.kwargs.get('channel'))
        if not channel.exists():
            return HttpResponseRedirect(reverse('forumapp:channel'))

        channel = channel.get()

        if 'delete_thread' in request.POST:
            thread_id = request.POST['thread_id']
            thread = self.queryset.filter(channel=channel, thread_id=thread_id)

            if thread.exists():
                thread = thread.get()

                # Require staff, owner, or mod status to delete threads
                if request.user.is_staff or is_mod(thread, request.user):

                    thread.delete()

                else:
                    raise Http404("Insufficient permissions.")

            else:
                raise Http404("Couldn't find that channel.")

        elif 'delete_channel' in request.POST:

            if request.user.is_staff or is_owner(channel, request.user):
                channel.delete()

                return HttpResponseRedirect(reverse('forumapp:channel'))

            else:

forumapp/templates/forumapp/channel.html
{% extends 'base.html' %}
{% load channel_helpers %}
{% block content %}

<div class="clearfix">
    <button type="button" class="button float-right" data-open="newChannel">Create a new channel</button>
</div>

<a href="{% url 'forumapp:channel' %}">Forum</a> &gt; ...<hr>

{% include "forumapp/messages.html" %}

{% for listing in channel_list|minus_bans:request.user.get_username %}
  {% include "forumapp/channel_listing.html" %}
{% empty %}
  <p>No channels are available.</p>
{% endfor %}

<div class="reveal" id="newChannel" data-reveal>
	<h3>Create a new channel:</h3>
  <form method="post">
    {% csrf_token %}
      {{ form }}
    <button type="submit" class="success button float-right submit" name="create">Create Channel</button>
  </form>
	<button class="close-button" data-close aria-label="Close modal" type="button">
		<span aria-hidden="true">&times;</span>
	</button>

</div>
{% endblock %}

forumapp/templates/forumapp/channel_listing.html
{% load channel_helpers %}
<div class="callout panel">
  <div class="grid-x">
    <div class="small-9 medium-9 large-10 cell">
      <h3><a href="{% url 'forumapp:thread' channel=listing.channel_name %}">{{ listing }}</a></h3>
      {{ listing.description }}
    </div>
    <div class="small-1 cell">
      Owned by: {% include 'forumapp/user_listing.html' %}
    </div>

    <div class="small-2 medium-2 large-1 cell">
      <form action="#" method="post">
      {% csrf_token %}
      {% if request.user.is_staff %}
        <input type="hidden" value="{{ listing.channel_name }}" name="channel_name">
        {% if not listing.pin_date %}
          <input type="submit" class="primary button radius" value="Pin" name="pin" style="width:100%;">
        {% else %}
          <input type="submit" class="secondary button radius" value="Unpin" name="unpin" style="width:100%;">
        {% endif %}
      {% elif listing.pin_date %}
	<p style="text-align: center;">Pinned</p>
      {% endif %}

      {% if request.user.is_authenticated %}
        <input type="hidden" value="{{ listing.channel_name }}" name="channel_name">
        {% if not listing|is_favorite:request.user %}
          <input type="submit" class="success button radius" value="Favorite" name="add_favorite" style="width: 100%;">
        {% else %}
	  <input type="submit" class="secondary button radius" value="Unfavorite" name="remove_favorite" style="width: 100%;">
       {% endif %}
      {% endif %}
      </form>
    </div>
  </div>
</div>

forumapp/templates/forumapp/channel_settings.html
{% extends 'base.html' %}
{% block content %}
</br>
<div class="callout panel">
	<h2>Channel settings for {{ object }}</h2>
	{% include "forumapp/messages.html" %}
	
	<form action="#" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" class="primary button radius" value="Apply" name="save">
	</form>
</div>
{% endblock %}

forumapp/templates/forumapp/comment.html
{% extends 'base.html' %}
{% load comment_helpers %}
{% load common_helpers %}
{% block content %}

<div class="clearfix">
	<a href="{% url 'forumapp:thread' view.kwargs.channel %}" class="button" name="back">Back to {{ view.kwargs.channel }}</a>
	{% if view.kwargs|is_moderator:request.user or request.user.is_staff %}
		<button type="button" class="alert button float-right radius" data-open="deleteThread">Delete this thread</button>
	{% endif %}
	<button type="button" class="button float-right radius" data-open="newComment">Create a new comment</button>

</div>

<a href="{% url 'forumapp:channel' %}">Forum</a> &gt;
<a href="{% url 'forumapp:thread' view.kwargs.channel %}">{{ view.kwargs.channel }}</a> &gt;
<a href="{% url 'forumapp:comment' view.kwargs.channel view.kwargs.thread %}">{{ view.kwargs|get_thread_name }}
</a>&gt; ...<hr>

{% include "forumapp/messages.html" %}


{% if request.user|is_banned_from:view.kwargs.channel %}
    <p>Sorry, this channel is unavailable.</p>
{% else %}
    <h2>{{ view.kwargs|get_thread_name }}</h2>
    <h4>{{ view.kwargs|description }}</h4>
    <ul>
    {% for listing in comment_list|dictsortreversed:'pub_date' %}
      {% include 'forumapp/comment_listing.html' %}
    {% empty %}
        <p>No comments are available.</p>
    {% endfor %}
    </ul>
{% endif %}


<div class="reveal" id="newComment" data-reveal>
	<h3>Create a new comment:</h3>
	<form action="#" method="post" autofocus>
		{% csrf_token %}
	  	{{ form }}
		<button type="submit" class="success button float-right radius" name="create">Create Comment</button>
	</form>
	<button class="close-button" data-close aria-label="Close modal" type="button">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
<div class="reveal" id="deleteThread" data-reveal>
	<h3>Are you sure you want to delete this thread?</h3>
	<form action="#" method="post">
		{% csrf_token %}
		<input type="submit" class="alert button float-right radius" value="Delete this thread" name="delete_thread">
	</form>
</div>
{% endblock %}

forumapp/templates/forumapp/comment_listing.html
{% load comment_helpers %}
{% load common_helpers %}
{% load tz %}
<div class="callout panel grid-x">
	<div class="cell small-3 medium-2 large-1" align="center">
	  {% include 'forumapp/user_listing.html' %}</br>
	  {{ listing.pub_date|format_date }}
  </div>
	{% if request.user.is_staff or view.kwargs|is_moderator:request.user %}
	<div class="cell small-7 medium-8 large-10"><p>{{ listing.text }}</p></div>
	<div class="cell small-2 medium-2 large-1">
	  <form action="#" method="post">
		{% csrf_token %}
		<input type="hidden" value="{{ listing.comment_id }}" name="comment_id">
		<input type="submit" class="alert button float-right radius" value="Delete" name="delete_comment" style="width:100%;">
	  </form>
	</div>
	{% else %}
	<div class="cell small-11"><p>{{ listing.text }}</p></div>
	{% endif %}
    </div>

forumapp/templates/forumapp/favorites.html
{% extends 'base.html' %}
{% block content %}

{% if favorites_list %}
    {% for listing in favorites_list %}
      {% include "forumapp/channel_listing.html" %}
    {% endfor %}
{% else %}
    <p>You have no favorite channels.</p>
{% endif %}

{% endblock %}

forumapp/templates/forumapp/messages.html
{% for message in messages %}
  <div class="callout" data-closable>
    <button class="close-button" aria-label="Close alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

forumapp/templates/forumapp/thread.html
{% extends 'base.html' %}
{% load thread_helpers %}
{% load common_helpers %}
{% block content %}

<div class="clearfix">

		<a href="{% url 'forumapp:channel' %}" class="button" name="back">Back to Channels</a>

		{% if view.kwargs|is_owner:request.user or request.user.is_staff %}
			<a href="{% url 'forumapp:channel_settings' view.kwargs.channel %}" class="button" name="settings">Settings</a>
		{% endif %}

		{% if view.kwargs|is_owner:request.user or request.user.is_staff %}
			<button type="button" class="alert button float-right radius" data-open="deleteChannel">
				Delete this channel
			</button>
		{% endif %}

		<button type="button" class="button float-right radius" data-open="newThread">
			Create a new thread
		</button>

</div>

<a href="{% url 'forumapp:channel' %}">Forum</a> &gt;
<a href="{% url 'forumapp:thread' view.kwargs.channel %}">{{ view.kwargs.channel }}</a> &gt; ...<hr>

{% include "forumapp/messages.html" %}

{% if request.user|is_banned_from:view.kwargs.channel %}
  <p>Sorry, this channel is unavailable.</p>
{% else %}
  <h2>{{ view.kwargs.channel }} </h2>
  <h4>{{ view.kwargs.channel|description }}</h4>
  {% for listing in thread_list %}
    {% include "forumapp/thread_listing.html" %}
  {% empty %}
    <p>No threads are available.</p>
  {% endfor %}
{% endif %}

<div class="reveal" id="newThread" data-reveal>
	<h3>Create a new thread:</h3>
	<form action="#" method="post">
		{% csrf_token %}
	  	{{ form }}
		<button type="submit" class="success button float-right radius" name="create">Create Thread</button>
	</form>
	<button class="close-button" data-close aria-label="Close modal" type="button">
		<span aria-hidden="true">&times;</span>
	</button>
</div>

<div class="reveal" id="deleteChannel" data-reveal>
	<h3>Are you sure you want to delete your channel?</h3>
	<form action="#" method="post">
		{% csrf_token %}
		<input type="submit" class="alert button float-right radius" value="Delete this channel" name="delete_channel">
	</form>
</div>
{% endblock %}

forumapp/templates/forumapp/thread_listing.html
{% load common_helpers %}
<div class="row">
    <div class="callout panel radius grid-x">
	<div class="cell small-10">
		<h3><a href="{% url 'forumapp:comment' channel=listing.channel.channel_name thread=listing.thread_id %}">{{ listing.thread_name }}</a></h3>
      		{{ listing.description }}
	</div>
	<div class="cell small-1">
		Owned by: {% include 'forumapp/user_listing.html' %}
	</div>
	<div class="cell small-1">
	    {% if request.user.is_staff or view.kwargs|is_moderator:request.user %}
	    <form action="#" method="post">
		{% csrf_token %}
		    <input type="hidden" value="{{ listing.thread_id }}" name="thread_id">
		    {% if not request.user.is_staff %}
			    {% if not listing.pin_date %}
				<input type="submit" class="primary button radius" value="Pin" name="pin" style="width:100%;">
			    {% else %}
				<input type="submit" class="secondary button radius" value="Unpin" name="unpin" style="width:100%;">
			    {% endif %}
		    {% endif %}
		    <input type="submit" class="alert button float-right radius" value="Delete" name="delete_thread" style="width:100%;">

	    </form>
	    {% elif listing.pin_date %}
		<p style="text-align: center;">Pinned</p>
	    {% endif %}
	</div>

    </div>
</div>

forumapp/templates/forumapp/user_listing.html
<a href="{% url 'forumapp:user' username=listing.owner.username %}">{{ listing.owner.username }}</a>

forumapp/templates/forumapp/user_settings.html
{% extends 'base.html' %}
{% block content %}
</br>
<div class="callout panel">
	<h2>User settings for {{ object.user }}</h2>
	{% include "forumapp/messages.html" %}
	<a class="button" href="{% url 'registration:password_reset' %}">Reset your password</a>

	<form action="#" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" class="primary button radius" value="Apply" name="save">
	</form>
</div>
{% endblock %}