django_forum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
#    url(r'^foundation/', include('foundation.urls')),
    url(r'^forum/', include('forumapp.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='welcome')
]

forumapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'forumapp'
urlpatterns = [
    url(r'^settings/$', views.UserSettingsView.as_view(), name='settings'),
    url(r'^settings/(?P<channel>[-\w]+)/$', views.ChannelSettingsView.as_view(), name='channel_settings'),
    url(r'^favorites/$', views.FavoritesView.as_view(), name='favorites'),
    url(r'^user/(?P<username>[-\w]+)/$', views.UserView.as_view(), name='user'),
    url(r'^(?P<channel>[-\w]+)/(?P<thread>[0-9]+)/$', views.CommentView.as_view(), name='comment'),
    url(r'^(?P<channel>[-\w]+)/$', views.ThreadView.as_view(), name='thread'),
    url(r'^$', views.ChannelView.as_view(), name='channel'),
]

registration/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import SignUpView, LogInView, PasswordResetView, PasswordResetSuccessView

app_name = 'registration'
urlpatterns = [
    url(r'login/', LogInView, name='login'),
    url(r'logout/', auth_views.logout, {'template_name': 'registration/logout.html'}, name='logout'),
    url(r'signup/', SignUpView, name='signup'),
    url(r'password_reset/', PasswordResetView, name='password_reset'),
    url(r'password_reset_success/', PasswordResetSuccessView, name='password_reset_success'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <title>Forum</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css" integrity="sha256-ogmFxjqiTMnZhxCqVmcqTvjfe1Y/ec4WaRj/aQPvn+I=" crossorigin="anonymous">
</head>
<body>

<!--
  <div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text"><a href="/forum/">Forum</a></li>
        <li>
          <a href="#">One</a>
          <ul class="menu horizontal">
            <li><a href="/forum/test/">One</a></li>
            <li><a href="/forum/testing">Two</a></li>
            <li><a href="#">Three</a></li>
          </ul>
        </li>
        <li><a href="#">Two</a></li>
        <li><a href="#">Three</a></li>
      </ul>
    </div>
  </div>
-->

  <div class="top-bar" style='background: #60b8b8;'>
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu style='background: #60b8b8;'>
        <li class="menu-text">Forum</li>
        <li><a href="{% url 'forumapp:channel' %}" style='color: #1468a0'>Channels</a></li>
        <li><a href="{% url 'forumapp:favorites' %}" style='color: #1468a0'>Favorites</a></li>
        {% if request.user.is_staff %}
          <li><a href="{% url 'admin:index' %}" style='color: #1468a0'>Administration</a></li>
        {% endif %}
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu" style='background: #60b8b8;'>
        {% if request.user.is_authenticated %}
          <li class="menu-text">Welcome, {{ request.user.get_username }}</li>
          <li><a href="{% url 'registration:logout' %}" style='color: #1468a0'>Logout</a></li>
          <li><a href="{% url 'forumapp:settings' %}" style='color: #1468a0'>Settings</a></li>
        {% else %}
          <li class="menu-text">Welcome, guest.</li>
          <li><a href="{% url 'registration:login' %}" style='color: #1468a0'>Login</a></li>
          <li><a href="{% url 'registration:signup' %}" style='color: #1468a0'>Sign up</a></li>
        {% endif %}
      </ul>
    </div>
  </div>


  <div class='off-canvas-wrapper' style='word-wrap: break-word;'>
    <div class='grid-x'>
      <div class='cell small-10 small-offset-1 col-md-8'>
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js" integrity="sha256-pRF3zifJRA9jXGv++b06qwtSqX1byFQOLjqa2PTEb2o=" crossorigin="anonymous"></script>

  <script>
    $(document).foundation();
  </script>


</body>
</html>

templates/index.html
<h1>Welcome to our Forum!<h1>
<h3>Getting Started</h3>
You can head straight to <a href="{% url 'forumapp:channel' %}">/forum</a> to check out the forum app.
Create an account <a href="{% url 'registration:signup' %}">here</a> to be able to make posts.
<h3>Administration</h3>
Admin controls are located at <a href="{% url 'admin:index' %}">/admin</a>. Make sure you have run manage.py createsuperuser.